######################################################################
# Automatically generated by qmake (3.0) Thu Aug 11 00:57:03 2016
######################################################################

TARGET = jalapeno

CONFIG += ordered

SUBDIRS += common jalapeno

TEMPLATE = vcsubdirs
